@extends('base')

@section('content')
    @include('partials.home_sections.hero')
    @include('partials.home_sections.flash-product')
    @include('partials.home_sections.collection-product')
    @include('partials.home_sections.office-product')
    @include('partials.home_sections.school-product')
    @include('partials.home_sections.limited-product')
    @include('partials.home_sections.picks-product')
    @include('partials.home_sections.new-product')
    @include('partials.home_sections.center-banner')
    @include('partials.home_sections.opportunity-product')
    @include('partials.home_sections.info-banner')
    @include('partials.home_sections.dining-room')
    @include('partials.home_sections.vivense-best')
    @include('partials.home_sections.for-you-product')
    {{-- <x-for-you-products /> --}}
    @include('partials.home_sections.bottom-banner')
    @include('partials.home_sections.payment-slider')
    @include('partials.home_sections.populer-category')
    @include('partials.home_sections.footer-banner')
    @include('partials.home_sections.vivense-special')
    @include('partials.home_sections.cta')
@endsection
